[tool.poetry]
name = "chat-app"
version = "0.1.0"
description = ""
authors = ["Kla1mzZz <kla1mzz16@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
